### ISSUE TITLE
Not working on txcz-rk3229-mxq-v2.2

### ISSUE THREAD

**Issue by rbnvrw** [paolosabatino/armbian-build#1]
Thank you @paolosabatino for taking the time to port ARMbian for the TV box!

I tried booting the pre-built Armbian_20.05.0-trunk_Rk322x-box_buster_legacy_4.4.194_minimal.img image from an SD card, but I don't see anything happening (no blue LED).

The device is a MXQ pro 4k with the following printed on the board: txcz-rk3229-mxq-v2.2. I can attach pictures if needed. If useful, the following LibreELEC image is working for me: LibreELEC-RK322x.arm-9.2-devel-20200301143414-b58333a-rk3228a-mxq4kpro (but then there is no wifi).

Any ideas what I can do to fix/troubleshoot the armbian boot process? I'd be happy to help.

**Comment by paolosabatino** [comment]
The image requires a bit of setup on you box, follow the instruction on Armbian forum:
https://forum.armbian.com/topic/12656-wip-armbian-for-rk322x-devices/

**Comment by rbnvrw** [comment]
Thank you! I don't know how I missed that post, but the instructions were clear and it worked out of the box! Will this make it into the official armbian project? Let me know if I can help with anything & keep up the awesome work!

**Comment by paolosabatino** [comment]
You're welcome. Feel free to write to the forum for any request or problem. Any testing is very welcome!
I hope to merge the rk322x fork soon to main project
