### ISSUE TITLE
Add kernel support for usb gadgets

### ISSUE THREAD

**Issue by NewbieOrange** [paolosabatino/armbian-build#3]
Hi, I am trying to use the rk322x box as a usb gadget. The documentation from rockchip stated the chip supports it.

However the kernel config in this build seems have not enable it, can we add the compile options for usb gadgets?

Change the following config to yes should solve the issue.

```
CONFIG_USB_CONFIGFS_SERIAL=y
CONFIG_USB_CONFIGFS_ACM=y
CONFIG_USB_CONFIGFS_OBEX=y
CONFIG_USB_CONFIGFS_NCM=y
CONFIG_USB_CONFIGFS_ECM=y
CONFIG_USB_CONFIGFS_ECM_SUBSET=y
CONFIG_USB_CONFIGFS_RNDIS=y
CONFIG_USB_CONFIGFS_EEM=y
CONFIG_USB_CONFIGFS_MASS_STORAGE=y
CONFIG_USB_CONFIGFS_F_LB_SS=y
CONFIG_USB_CONFIGFS_F_FS=y
CONFIG_USB_CONFIGFS_F_UAC1=y
CONFIG_USB_CONFIGFS_F_UAC2=y
CONFIG_USB_CONFIGFS_F_MIDI=y
CONFIG_USB_CONFIGFS_F_HID=y
CONFIG_USB_CONFIGFS_F_UVC=y
CONFIG_USB_CONFIGFS_F_PRINTER=y
```

**Comment by paolosabatino** [comment]
It is possible indeed!
If you find that is stable and also the OTG port does not lose the regular USB host functionality there is no problem with this.

**Comment by paolosabatino** [comment]
Also which kernel are you exactly referring to?

**Comment by NewbieOrange** [comment]
All rk322x ones, preferably. I personally use the legacy one.

**Comment by NewbieOrange** [comment]
Not sure whats wrong, but the build output has no linux-image deb for me.

```
  INSTALL sound/soc/codecs/snd-soc-rk3228.ko
  INSTALL sound/soc/codecs/snd-soc-tc358749x.ko
  DEPMOD  4.4.194-rk322x
[ o.k. ] Building deb [ armbian-config ]
[ o.k. ] Checking git sources [ armbian-config master ]
[ .... ] Up to date 
[ o.k. ] Checking git sources [ neofetch 7.1.0 ]
[ .... ] Up to date 
[ o.k. ] Checking git sources [ wireguard-manager v1.0.0.06-20-2021 ]
[ .... ] Up to date 
[ o.k. ] * applying add-armbian-neofetch.patch 
[ o.k. ] Building deb [ armbian-zsh ]
[ o.k. ] Checking git sources [ oh-my-zsh master ]
[ .... ] Up to date 
[ o.k. ] Checking git sources [ evalcache master ]
[ .... ] Up to date 
[ o.k. ] Merging and packaging linux firmware [ @host ]
[ o.k. ] Checking git sources [ armbian-firmware-git master ]
[ .... ] Up to date 
[ o.k. ] Building firmware package [ armbian-firmware_21.11.0-trunk_all ]
[ o.k. ] Merging and packaging linux firmware [ @host ]
[ o.k. ] Checking git sources [ armbian-firmware-git master ]
[ .... ] Up to date 
[ o.k. ] Checking git sources [ linux-firmware-git master ]
[ .... ] Up to date 
[ o.k. ] Building firmware package [ armbian-firmware-full_21.11.0-trunk_all ]
[ o.k. ] Creating board support package for CLI [ armbian-bsp-cli-rk322x-box ]
[ o.k. ] Kernel build done [ @host ]
[ o.k. ] Target directory [ /home/chengzi/armbian-build-rk3229/output/debs/ ]
[ o.k. ] File name [ linux-image-legacy-rk322x_21.11.0-trunk_armhf.deb ]
[ o.k. ] Runtime [ 3 min ]
[ o.k. ] Repeat Build Options [ ./compile.sh  BOARD=rk322x-box BRANCH=legacy RELEASE=buster BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_ONLY=yes KERNEL_CONFIGURE=yes  ]
```

Can you build a legacy kernel with usb gadgets and modules enabled? or please point out why the build have no kernel deb.

**Comment by NewbieOrange** [comment]
I figured this is not a kernel issue, rather the dtb file set the port to host.

I suppose we can set that port to peripheral? Rk322x boxes have 4 USB port, having one as peripheral should not hurt.

If that is undesired, having an alternative dtb for users to choose is nice too.

**Comment by paolosabatino** [comment]
There are devices with only two ports and losing one for niche cases is not a good idea.
A device tree overlay can be a workaround solution, but normally the port should autoconfigure itself if `dr_mode` is set to `otg` in the device tree, which is the proper way to go.
I never tested this, it should be possible for the port to autoconfigure if a feedback wire to detect voltage on USB line is set up correctly (don't know if dtb requires changes) and the kernel drivers should be capable of changing mode.

**Comment by NewbieOrange** [comment]
Sadly seems I am wrong, kernel configuration modifications are still needed, otherwise cannot create gadget with specific functions (as HID device, for example).

![Screenshot](https://user-images.githubusercontent.com/7200314/142246788-633eb640-41d6-45e6-b252-ffe04557ba11.png)

Only enabling those gadgets support should not affect anything, unless the device tree set it to work as usb slave.

**Comment by NewbieOrange** [comment]
Yes the `otg` mode indeed support both way, however does require a special directional OTG cable.

**Comment by NewbieOrange** [comment]
Confirmed it is working fine, PiKvm runs flawlessly!

I have set `CONFIG_USB_CONFIGFS_MASS_STORAGE` and `CONFIG_USB_CONFIGFS_F_HID` to y. Some other options seem to make the kernel not compile correctly, not sure why tho.

**Comment by paolosabatino** [comment]
I will take a look and see if can enable it in dr_mode="otg" without losing regular host functionality

**Comment by NewbieOrange** [comment]
Can we have the kernel options enabled? The users can modify dr_mode in the dtb file if needed, but recompiling the kernel will take a long time. 😄

**Comment by paolosabatino** [comment]
It would be much better if you share the way you got USB otg port working and your use case.
I did my otg tests at the time but nothing was working.

**Comment by NewbieOrange** [comment]
Hi,

I am using pikvm with modified scripts on armbian: https://github.com/xe5700/kvmd-armbian

With dr_mode set to peripheral, connect a USB Type-A male-to-male cable to the host computer allowed the device to work as a KVM over IP device. If the box has a micro usb port (mine box's otg port is type-A), a special USB otg cable might work with dr_mode set to otg.

![PiKVM](https://user-images.githubusercontent.com/7200314/156917109-8fabc169-8252-401b-b286-46fc2f8c463c.png)

**Comment by NewbieOrange** [comment]
To get the USB port to work as USB HID / Mass storage peripherals, `CONFIG_USB_CONFIGFS_MASS_STORAGE` and `CONFIG_USB_CONFIGFS_F_HID` have been set to `y` in kernel config. After reinstall the new compiled kernel and dtb files, PiKVM works as expected.

**Comment by paolosabatino** [comment]
Thanks for you support, I made this commit https://github.com/paolosabatino/armbian-build/commit/9ebfb5ae70273bc2cbec195a654780aa07d1a3da and I hope everything is in place
