### ISSUE TITLE
Problem found in ...

### ISSUE THREAD

**Issue by dvarrel** [paolosabatino/armbian-build#5]
i tried compile full os image 
- rk3318-box,
- focal standard image server,
- use precompiled packages
-  with rk3318 branch repository 
the error at the end :
[ error ] ERROR in function install_deb_chroot [ image-helpers.sh:202 ]
[ error ] Installation of linux-u-boot-rk3318-box-current failed [ rk3318-box focal no rockchip64 ]
[ o.k. ] Process terminated 
[ o.k. ] Unmounting [ /home/dam/Bureau/h96/armbian-build/.tmp/rootfs-5396fe2c-7e1c-4745-b94e-542f1ba6e07f/ ]
[ error ] ERROR in function unmount_on_exit [ image-helpers.sh:82 ]
[ error ] debootstrap-ng was interrupted 
[ o.k. ] Process terminated 

my os : ubuntu 21.10

**Comment by paolosabatino** [comment]
Fixed an error in the device tree and updated to latest upstream. Thanks.

As a sidenote: Ubuntu 21.04 is the currently only officially supported building environment for Armbian, any other distribution is not guaranteed to work correctly.

**Comment by dvarrel** [comment]
i'll test with 21.04

**Comment by dvarrel** [comment]
i've tested with 21.04, after "git pull" rk3318 branch.
here's the errors :
[ o.k. ] Applying distribution specific tweaks for [ focal ]
[ o.k. ] Applying common tweaks 
[ .... ] Updating [ package lists ]
[ .... ] Temporarily disabling [ initramfs-tools hook for kernel ]
[ .... ] Installing from repository [ linux-u-boot-rk3318-box-current ]
[ error ] ERROR in function install_deb_chroot [ image-helpers.sh:202 ]
[ error ] Installation of linux-u-boot-rk3318-box-current failed [ rk3318-box focal no rockchip64 ]
[ o.k. ] Process terminated 
[ o.k. ] Unmounting [ /home/dam/armbian-build/.tmp/rootfs-734ba33a-148d-49a9-804b-dbedff919e2f/ ]
[ error ] ERROR in function unmount_on_exit [ image-helpers.sh:82 ]
[ error ] debootstrap-ng was interrupted 
[ o.k. ] Process terminated

**Comment by paolosabatino** [comment]
Perhaps this can help? https://forum.armbian.com/topic/18941-cannot-build-armbian-for-mele-a1000-error-in-function-install_deb_chroot/

You should ask in the community p2p help (not developer, nor the boards) part of the armbian forum, this repository is mostly for development on unofficial hardware.
