### ISSUE TITLE
rk3318-box

### ISSUE THREAD

**Issue by gzxief** [paolosabatino/armbian-build#6]
rk3318-box，BRANCH=current RELEASE=jammy，is error，but BRANCH=current RELEASE=hirsute，IS OK，thanks!!

**Comment by gzxief** [comment]
copy https://github.com/armbian/build/tree/master/config/cli/jammy to /root/armbian-build-rk3318/config/cli/jammy ,isOK

**Comment by paolosabatino** [comment]
Branch is not always aligned to mainline armbian, such kind of issues are usually solved in upstream repository.
I close this because probably will be "automatically" fixed on next align
